
#端口号
server:
  port: 8001

#服务名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver    #mysql驱动包
    url: jdbc:mysql://localhost:3306/spring_cloud_db_2020?serverTimezone=UTC&useUnicode=ture&characterEncodig=utf-8&useSSl=false #&serverTimezone=Asia/Shanghai
    username: root
    password: zzz0609

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zzz.wilson.lai.entities #所有Entity别名类所在的包

# Eureka Client相关配置
eureka:
  client:
    register-with-eureka: true #true表示是否将自己注册到EurekaServer默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版本的，将其注册到多个注册中心
#      defaultZone: http://localhost:7001/eureka #注册中心地址（单机注册中心版本）
  instance:
    instance-id: payment8001 #完善Eureka Server的服务信息，一般设置为服务器ip:端口
    prefer-ip-address: true #访问路径可以显式ip地址
    lease-renewal-interval-in-seconds: 1      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 2  # 发呆时间，即服务续约到期时间（缺省为90s）